# run: conda env create --file environment.yml
# include new packages: conda env update --file environment.yml
name: batch_copy_issues
channels:
  - conda-forge
  - conda
dependencies:
- anaconda
- conda:
  - numpy>=1.19
  - pytest=6.1.2
  - selenium
- pip
- pip:
  # works for regular pip packages
  - testbook
  - pyment
  - pdoc3
  - black
  - vulture